Wip add apidoc support
RBMHTechnology/apidoc-server pull request #17
Opened 2018-06-07 11:06 UTC by seakayone

fixes #12

2018-06-07 18:21 UTC, aconstantin commented
will have a look next week. thanks for investing so much effort

2018-07-02 09:16 UTC, aconstantin requested changes

2018-07-02 09:16 UTC, aconstantin commented on gradle/wrapper/gradle-wrapper.properties
> +distributionUrl=https\://services.gradle.org/distributions/gradle-4.5.1-bin.zip
should be 4.8 or better 4.8.1

2018-07-02 09:16 UTC, aconstantin commented on build.gradle
> +wrapper.gradleVersion = '4.8'
4.8.1

2018-07-02 09:16 UTC, aconstantin commented on src/main/java/com/rbmhtechnology/apidocserver/service/mavenrepo/MavenRepoClient.java
> +      BasicAuthScope scope = new BasicAuthScope();
those 4 lines, should be extracted from the mapping lambda

2018-07-02 09:16 UTC, aconstantin commented on src/main/java/com/rbmhtechnology/apidocserver/controller/ApiDocController.java
> +    this. repositoryUrl = mavenConfig.repositoryUrl();
formatting

2018-07-02 09:16 UTC, aconstantin commented on readme.md
> +* `classifier` (optional): The documentation classifier to be shown. Typical values are `javadoc`, `scaladoc`, `groovydoc` and so on.
describe behaviour if omitted

2018-07-02 09:35 UTC, seakayone commented
@aconstantin: Addressed your change requests for this pull request, please have another look.

2018-07-02 09:37 UTC, aconstantin approved these changes

2018-07-02 09:49 UTC, seakayone commented
I have rebased the branch and clean up some commits as discussed offline, this is ready to be merged now.

2018-07-02 10:01 UTC, merged